[package]
name = "sonata"
version = "0.1.0"
description = "Pure Rust media container and audio codec library."
authors = ["Philip Deljanov <philip.deljanov@gmail.com>"]
license = "LGPL-2.1-only"
readme = "README.md"
categories = ["multimedia"]
keywords = ["audio", "codec", "decoder", "encoder", "format"]

edition = "2018"

[features]
default = ["sonata-format-wav", "sonata-codec-flac", "sonata-codec-pcm"]
flac = ["sonata-codec-flac"]
pcm = ["sonata-codec-pcm"]
wav = ["sonata-format-wav"]

[dependencies]
sonata-codec-flac = { version = "*", path = "../sonata-codec-flac", optional = true }
sonata-codec-pcm = { version = "*", path = "../sonata-codec-pcm", optional = true }
sonata-format-wav = { version = "*", path = "../sonata-format-wav", optional = true }
