[package]
name = "symphonia-codec-aac"
version = "0.0.1"
description = "Pure Rust AAC decoder (a part of project Symphonia)."
homepage = "https://github.com/pdeljanov/Symphonia"
repository = "https://github.com/pdeljanov/Symphonia"
authors = ["Philip Deljanov <philip.deljanov@gmail.com>"]
license = "MPL-2.0"
readme = "README.md"
categories = ["multimedia", "multimedia::audio", "multimedia::encoding"]
keywords = ["audio", "codec", "decoder", "aac", "m4a"]
edition = "2018"

[dependencies]
log = "0.4"
symphonia-core = { version = "0.1", path = "../symphonia-core" }