[workspace]

members = [
    "symphonia",
    "symphonia-codec-aac",
    "symphonia-codec-flac",
    "symphonia-codec-mp3",
    "symphonia-codec-opus",
    "symphonia-codec-pcm",
    "symphonia-codec-vorbis",
    "symphonia-codec-wavpack",
    "symphonia-core",
    "symphonia-format-isomp4",
    "symphonia-format-mkv",
    "symphonia-format-ogg",
    "symphonia-format-wav",
    "symphonia-metadata",
    "symphonia-play",
    "symphonia-utils-xiph",
]
