[workspace]

members = [
    "symphonia",
    "symphonia-play",
    "symphonia-metadata",
    "symphonia-format-wav",
    "symphonia-format-ogg",
    "symphonia-core",
    "symphonia-codec-pcm",
    "symphonia-codec-mp3",
    "symphonia-codec-flac",
    "symphonia-utils-xiph",
]
