[package]
name = "sonata-core"
version = "0.1.0"
description = "Sonata shared structs, traits, and features."
authors = ["Philip Deljanov <philip.deljanov@gmail.com>"]
license = "LGPL-2.1-only"
readme = "README.md"
categories = ["multimedia"]
keywords = ["audio", "codec", "decoder", "encoder", "format"]

edition = "2018"

[dependencies]
lazy_static = "1.3.0"